# Generated by Django 4.1.7 on 2023-04-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crud",
            name="firstname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="crud",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="crud",
            name="lastname",
            field=models.CharField(default="", max_length=255),
        ),
    ]
