# Generated by Django 4.1.7 on 2023-04-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0002_alter_crud_firstname_alter_crud_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="crud", name="image",),
    ]
