# Generated by Django 4.1.7 on 2023-04-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0004_crud_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="crud", name="image",),
    ]
