# Generated by Django 4.1.7 on 2023-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0005_remove_crud_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crud",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
