# Generated by Django 4.1.7 on 2023-04-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0007_crud_upload_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="crud", name="upload_time",),
    ]
