# Generated by Django 4.1.7 on 2023-04-22 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0010_remove_crud_upload_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction", models.CharField(default="", max_length=255)),
                (
                    "fid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRUD.crud"
                    ),
                ),
            ],
        ),
    ]
