# Generated by Django 4.1.7 on 2023-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0012_pred_upload_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pred", name="upload_time", field=models.DateTimeField(),
        ),
    ]
